version: "3.8"

services:
  transaction-producer:
    build: ./transaction-producer
    container_name: transaction_producer
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    restart: always

  transaction-consumer:
    build: ./transaction-consumer
    container_name: transaction_consumer
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATA_MONGODB_URI: mongodb+srv://pavlovmiroslav92:Q9cIj0mveskCPAAT@cluster135.4xns2.mongodb.net/Spirit
    restart: always

volumes:
  mongo_data:
    driver: local